version: '3.8'
services:
  backend:
    env_file:
      - .env.local
    build:
      context: ./backend
      args:
        - FLASK_APP=${FLASK_APP}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: always